In [52]:
!pip install boto3 s3fs openpyxl

Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (1.43.62)
Requirement already satisfied: s3fs in /usr/local/lib/python3.12/dist-packages (0.4.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: botocore<1.44.0,>=1.43.62 in /usr/local/lib/python3.12/dist-packages (from boto3) (1.43.62)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from boto3) (0.19.2)
Requirement already satisfied: fsspec>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from s3fs) (2025.3.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<1.44.0,>=1.43.62->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.44.0,>=1.43.62->boto3) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.62->boto3) (1.17.0)

In [53]:
ACCESS_KEY = "AKIA6JDZK74LGYZWCAVA"
SECRET_KEY = "AKIA6JDZK74LGYZWCAVA"

In [56]:
import pandas as pd

df = pd.read_excel(
    "s3://machine-learning-dataset/ML Dataset.xlsx",
    storage_options={
        "key": "AKIA6JDZK74LCP7MDKGZ",
        "secret": "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"
    }
)

df.head()

,Vehicle_ID,Manufacturer,Model,Vehicle_Age,Engine_CC,Horsepower,Vehicle_Weight,Transmission,Fuel_Type,Ethanol_Blend,...,Traffic_Level,Temperature,Humidity,Weather,AC_Usage,Driving_Style,Passengers,CO2_Emission_g_km,Fuel_Consumption_L_100km,Mileage_km_per_L
0,V014767,Tata,Nexon,13.0,1000.0,82.0,1307.0,Automatic,Petrol,20.0,...,High,27.0,61.0,Fog,No,Normal,1.0,192.1,5.00,20.02
1,V020736,Toyota,Glanza,8.0,1200.0,98.0,1493.0,Automatic,Petrol,20.0,...,High,30.0,48.0,Fog,Yes,Smooth,3.0,189.2,5.12,19.52
2,V041583,Maruti,Baleno,9.0,1200.0,103.0,1262.0,Automatic,Petrol,20.0,...,Medium,34.0,44.0,Fog,Yes,Aggressive,1.0,197.3,5.55,18.01
3,V042258,Honda,City,14.0,1200.0,95.0,1001.0,Manual,Petrol,10.0,...,High,15.0,53.0,Rain,Yes,Normal,1.0,185.8,5.23,19.12
4,V029600,Tata,Altroz,15.0,1800.0,148.0,1604.0,Manual,Petrol,10.0,...,Medium,24.0,65.0,Fog,Yes,Smooth,1.0,197.7,5.90,16.96

In [57]:
import boto3

ACCESS_KEY = "AKIA6JDZK74LCP7MDKGZ"
SECRET_KEY = "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"

s3 = boto3.client(
    "s3",
    region_name="eu-north-1",
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY
)

print(s3.list_buckets())

{'ResponseMetadata': {'RequestId': '9T8ADHADC71YH84M', 'HostId': '9B1Ch/1IGf0YTvsWm8DN1pg1O3eBzetr5M3BOSC6K3qCasYB50OhqjfWag+qdlVfgRd2VkTtjOUz/3SPIjieWbSS1VE7Izgw', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': '9B1Ch/1IGf0YTvsWm8DN1pg1O3eBzetr5M3BOSC6K3qCasYB50OhqjfWag+qdlVfgRd2VkTtjOUz/3SPIjieWbSS1VE7Izgw', 'x-amz-request-id': '9T8ADHADC71YH84M', 'date': 'Sat, 01 Aug 2026 16:45:17 GMT', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 0}, 'Buckets': [{'Name': 'harsha-bucket15', 'CreationDate': datetime.datetime(2026, 5, 5, 11, 59, 10, tzinfo=tzlocal()), 'BucketArn': 'arn:aws:s3:::harsha-bucket15'}, {'Name': 'harsha-bucooo', 'CreationDate': datetime.datetime(2026, 5, 5, 18, 44, 57, tzinfo=tzlocal()), 'BucketArn': 'arn:aws:s3:::harsha-bucooo'}, {'Name': 'lab-demo100', 'CreationDate': datetime.datetime(2026, 4, 30, 7, 37, 5, tzinfo=tzlocal()), 'BucketArn': 'arn:aws:s3:::lab-demo100'}, {'Name': 'machine-learning-dataset', 'CreationDate': datetime.datetime(2026, 8, 1, 15, 3, 34, tzinfo=tzlocal()), 'BucketArn': 'arn:aws:s3:::machine-learning-dataset'}, {'Name': 'real-time-transaction', 'CreationDate': datetime.datetime(2026, 7, 27, 14, 25, 55, tzinfo=tzlocal()), 'BucketArn': 'arn:aws:s3:::real-time-transaction'}], 'Owner': {'ID': '31ceb2364e9032cac7eacbf204297ff435d5f8ca41c807bd1dd0b9003467900b'}}

In [58]:
response = s3.list_objects_v2(Bucket="machine-learning-dataset")
print(response)

{'ResponseMetadata': {'RequestId': 'FJ0BQTE0S75KWP5Z', 'HostId': '6mf6cVfhDdBlFmm6dis1rj3XCetK7EhLJnjWRtCXopyP9dJrfkG7glW5lsb/Td+IDgzt1z8zS1Lka5pZblCRNL476+n38h2k', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': '6mf6cVfhDdBlFmm6dis1rj3XCetK7EhLJnjWRtCXopyP9dJrfkG7glW5lsb/Td+IDgzt1z8zS1Lka5pZblCRNL476+n38h2k', 'x-amz-request-id': 'FJ0BQTE0S75KWP5Z', 'date': 'Sat, 01 Aug 2026 16:45:20 GMT', 'x-amz-bucket-region': 'eu-north-1', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Contents': [{'Key': 'ML Dataset.xlsx', 'LastModified': datetime.datetime(2026, 8, 1, 15, 4, 52, tzinfo=tzlocal()), 'ETag': '"ca7a4e554e8a53d6cdfaffc2800e89ac"', 'ChecksumAlgorithm': ['CRC64NVME'], 'ChecksumType': 'FULL_OBJECT', 'Size': 10001447, 'StorageClass': 'STANDARD'}], 'Name': 'machine-learning-dataset', 'Prefix': '', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 1}

In [59]:
import pandas as pd

ACCESS_KEY = " AKIA6JDZK74LCP7MDKGZ"
SECRET_KEY = "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"

df = pd.read_excel(
    "s3://machine-learning-dataset/ML Dataset.xlsx",
    storage_options={
        "key": ACCESS_KEY,
        "secret": SECRET_KEY,
        "client_kwargs": {
            "region_name": "eu-north-1"
        }
    }
)

df.head()

,Vehicle_ID,Manufacturer,Model,Vehicle_Age,Engine_CC,Horsepower,Vehicle_Weight,Transmission,Fuel_Type,Ethanol_Blend,...,Traffic_Level,Temperature,Humidity,Weather,AC_Usage,Driving_Style,Passengers,CO2_Emission_g_km,Fuel_Consumption_L_100km,Mileage_km_per_L
0,V014767,Tata,Nexon,13.0,1000.0,82.0,1307.0,Automatic,Petrol,20.0,...,High,27.0,61.0,Fog,No,Normal,1.0,192.1,5.00,20.02
1,V020736,Toyota,Glanza,8.0,1200.0,98.0,1493.0,Automatic,Petrol,20.0,...,High,30.0,48.0,Fog,Yes,Smooth,3.0,189.2,5.12,19.52
2,V041583,Maruti,Baleno,9.0,1200.0,103.0,1262.0,Automatic,Petrol,20.0,...,Medium,34.0,44.0,Fog,Yes,Aggressive,1.0,197.3,5.55,18.01
3,V042258,Honda,City,14.0,1200.0,95.0,1001.0,Manual,Petrol,10.0,...,High,15.0,53.0,Rain,Yes,Normal,1.0,185.8,5.23,19.12
4,V029600,Tata,Altroz,15.0,1800.0,148.0,1604.0,Manual,Petrol,10.0,...,Medium,24.0,65.0,Fog,Yes,Smooth,1.0,197.7,5.90,16.96

In [60]:
print(df.head())
print(df.shape)

  Vehicle_ID Manufacturer   Model  Vehicle_Age  Engine_CC  Horsepower  \
0    V014767         Tata   Nexon         13.0     1000.0        82.0
1    V020736       Toyota  Glanza          8.0     1200.0        98.0
2    V041583       Maruti  Baleno          9.0     1200.0       103.0
3    V042258        Honda    City         14.0     1200.0        95.0
4    V029600         Tata  Altroz         15.0     1800.0       148.0

   Vehicle_Weight Transmission Fuel_Type  Ethanol_Blend  ...  Traffic_Level  \
0          1307.0    Automatic    Petrol           20.0  ...           High
1          1493.0    Automatic    Petrol           20.0  ...           High
2          1262.0    Automatic    Petrol           20.0  ...         Medium
3          1001.0       Manual    Petrol           10.0  ...           High
4          1604.0       Manual    Petrol           10.0  ...         Medium

   Temperature  Humidity  Weather  AC_Usage Driving_Style Passengers  \
0         27.0      61.0      Fog        No        Normal        1.0
1         30.0      48.0      Fog       Yes        Smooth        3.0
2         34.0      44.0      Fog       Yes    Aggressive        1.0
3         15.0      53.0     Rain       Yes        Normal        1.0
4         24.0      65.0      Fog       Yes        Smooth        1.0

  CO2_Emission_g_km  Fuel_Consumption_L_100km  Mileage_km_per_L
0             192.1                      5.00             20.02
1             189.2                      5.12             19.52
2             197.3                      5.55             18.01
3             185.8                      5.23             19.12
4             197.7                      5.90             16.96

[5 rows x 27 columns]
(64849, 27)

In [61]:
df.columns

Index(['Vehicle_ID', 'Manufacturer', 'Model', 'Vehicle_Age', 'Engine_CC',
       'Horsepower', 'Vehicle_Weight', 'Transmission', 'Fuel_Type',
       'Ethanol_Blend', 'Fuel_Price', 'Trip_Distance_km', 'Average_Speed',
       'Engine_RPM', 'Tire_Pressure_PSI', 'Maintenance_Status', 'Road_Type',
       'Traffic_Level', 'Temperature', 'Humidity', 'Weather', 'AC_Usage',
       'Driving_Style', 'Passengers', 'CO2_Emission_g_km',
       'Fuel_Consumption_L_100km', 'Mileage_km_per_L'],
      dtype='object')

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64849 entries, 0 to 64848
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Vehicle_ID                64848 non-null  object
 1   Manufacturer              64847 non-null  object
 2   Model                     64848 non-null  object
 3   Vehicle_Age               64554 non-null  float64
 4   Engine_CC                 64848 non-null  float64
 5   Horsepower                64845 non-null  float64
 6   Vehicle_Weight            64847 non-null  float64
 7   Transmission              64846 non-null  object
 8   Fuel_Type                 64848 non-null  object
 9   Ethanol_Blend             64848 non-null  float64
 10  Fuel_Price                64848 non-null  float64
 11  Trip_Distance_km          64846 non-null  float64
 12  Average_Speed             64846 non-null  float64
 13  Engine_RPM                64844 non-null  float64
 14  Tire_Pressure_PSI         64847 non-null  float64
 15  Maintenance_Status        64847 non-null  object
 16  Road_Type                 64847 non-null  object
 17  Traffic_Level             64849 non-null  object
 18  Temperature               64847 non-null  float64
 19  Humidity                  64846 non-null  float64
 20  Weather                   64845 non-null  object
 21  AC_Usage                  64848 non-null  object
 22  Driving_Style             64848 non-null  object
 23  Passengers                64845 non-null  float64
 24  CO2_Emission_g_km         64848 non-null  float64
 25  Fuel_Consumption_L_100km  64848 non-null  float64
 26  Mileage_km_per_L          64515 non-null  float64
dtypes: float64(16), object(11)
memory usage: 13.4+ MB

In [63]:
print("Duplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("After removing duplicates:", len(df))

Duplicate Rows: 546
After removing duplicates: 64303

In [64]:
df.isnull().sum()

Vehicle_ID                    1
Manufacturer                  2
Model                         1
Vehicle_Age                 293
Engine_CC                     1
Horsepower                    4
Vehicle_Weight                2
Transmission                  3
Fuel_Type                     1
Ethanol_Blend                 1
Fuel_Price                    1
Trip_Distance_km              3
Average_Speed                 3
Engine_RPM                    5
Tire_Pressure_PSI             2
Maintenance_Status            2
Road_Type                     2
Traffic_Level                 0
Temperature                   2
Humidity                      3
Weather                       4
AC_Usage                      1
Driving_Style                 1
Passengers                    4
CO2_Emission_g_km             1
Fuel_Consumption_L_100km      1
Mileage_km_per_L            330
dtype: int64

In [65]:
# Columns to remove
columns_to_drop = [
    "Vehicle_ID",
    "Manufacturer",
    "Model",
    "CO2_Emission_g_km",
    "Fuel_Consumption_L_100km"
]

# Drop the columns
df = df.drop(columns=columns_to_drop)

# Verify the remaining columns
print(df.columns)

Index(['Vehicle_Age', 'Engine_CC', 'Horsepower', 'Vehicle_Weight',
       'Transmission', 'Fuel_Type', 'Ethanol_Blend', 'Fuel_Price',
       'Trip_Distance_km', 'Average_Speed', 'Engine_RPM', 'Tire_Pressure_PSI',
       'Maintenance_Status', 'Road_Type', 'Traffic_Level', 'Temperature',
       'Humidity', 'Weather', 'AC_Usage', 'Driving_Style', 'Passengers',
       'Mileage_km_per_L'],
      dtype='object')

In [66]:
df.shape

(64303, 22)

In [67]:
df.isnull().sum()

Vehicle_Age           293
Engine_CC               1
Horsepower              4
Vehicle_Weight          2
Transmission            3
Fuel_Type               1
Ethanol_Blend           1
Fuel_Price              1
Trip_Distance_km        3
Average_Speed           3
Engine_RPM              5
Tire_Pressure_PSI       2
Maintenance_Status      2
Road_Type               2
Traffic_Level           0
Temperature             2
Humidity                3
Weather                 4
AC_Usage                1
Driving_Style           1
Passengers              4
Mileage_km_per_L      330
dtype: int64

In [68]:
df.dtypes

Vehicle_Age           float64
Engine_CC             float64
Horsepower            float64
Vehicle_Weight        float64
Transmission           object
Fuel_Type              object
Ethanol_Blend         float64
Fuel_Price            float64
Trip_Distance_km      float64
Average_Speed         float64
Engine_RPM            float64
Tire_Pressure_PSI     float64
Maintenance_Status     object
Road_Type              object
Traffic_Level          object
Temperature           float64
Humidity              float64
Weather                object
AC_Usage               object
Driving_Style          object
Passengers            float64
Mileage_km_per_L      float64
dtype: object

In [69]:
# Display unique values for every categorical column

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    print("="*40)
    print(f"{col}")
    print(df[col].unique())

========================================
Transmission
['Automatic' 'Manual' nan]
========================================
Fuel_Type
['Petrol' nan]
========================================
Maintenance_Status
['Average' 'Poor' 'Good' nan]
========================================
Road_Type
['Highway' 'Mixed' 'Rural' 'City' nan]
========================================
Traffic_Level
['High' 'Medium' 'Low']
========================================
Weather
['Fog' 'Rain' 'Clear' nan]
========================================
AC_Usage
['No' 'Yes' nan]
========================================
Driving_Style
['Normal' 'Smooth' 'Aggressive' nan]

In [70]:
#Remove Extra Spaces
for col in cat_cols:
    df[col] = df[col].str.strip()

In [71]:
#Standardize Text
for col in cat_cols:
    df[col] = df[col].str.title()

In [72]:
from sklearn.impute import SimpleImputer
#Fill categorical missing values using Mode
cat_imputer = SimpleImputer(strategy="most_frequent")

df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

In [73]:
df.isnull().sum()

Vehicle_Age           293
Engine_CC               1
Horsepower              4
Vehicle_Weight          2
Transmission            0
Fuel_Type               0
Ethanol_Blend           1
Fuel_Price              1
Trip_Distance_km        3
Average_Speed           3
Engine_RPM              5
Tire_Pressure_PSI       2
Maintenance_Status      0
Road_Type               0
Traffic_Level           0
Temperature             2
Humidity                3
Weather                 0
AC_Usage                0
Driving_Style           0
Passengers              4
Mileage_km_per_L      330
dtype: int64

In [74]:
#Seperate numerical columns

num_cols = df.select_dtypes(include=['int64', 'float64']).columns

In [75]:
#Fill numerical missing values using Median
num_imputer = SimpleImputer(strategy="median")

df[num_cols] = num_imputer.fit_transform(df[num_cols])

In [76]:
df.isnull().sum()

Vehicle_Age           0
Engine_CC             0
Horsepower            0
Vehicle_Weight        0
Transmission          0
Fuel_Type             0
Ethanol_Blend         0
Fuel_Price            0
Trip_Distance_km      0
Average_Speed         0
Engine_RPM            0
Tire_Pressure_PSI     0
Maintenance_Status    0
Road_Type             0
Traffic_Level         0
Temperature           0
Humidity              0
Weather               0
AC_Usage              0
Driving_Style         0
Passengers            0
Mileage_km_per_L      0
dtype: int64

In [77]:
df.shape

(64303, 22)

#Outlier Detection

Use the IQR method to see how many outliers each numeric feature has.

In [78]:
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col} : {len(outliers)}")

Vehicle_Age : 0
Engine_CC : 0
Horsepower : 0
Vehicle_Weight : 0
Ethanol_Blend : 0
Fuel_Price : 0
Trip_Distance_km : 0
Average_Speed : 0
Engine_RPM : 0
Tire_Pressure_PSI : 0
Temperature : 0
Humidity : 0
Passengers : 0
Mileage_km_per_L : 298

#Remove Outliers

In [79]:
target = "Mileage_km_per_L"

numeric_columns = [col for col in numeric_columns if col != target]

for col in numeric_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

In [80]:
df.shape

(64303, 22)

#One-Hot Encoding

Dataset has nominal categorical variables, One-Hot Encoding is the correct choice.

In [81]:
cat_cols

Index(['Transmission', 'Fuel_Type', 'Maintenance_Status', 'Road_Type',
       'Traffic_Level', 'Weather', 'AC_Usage', 'Driving_Style'],
      dtype='object')

In [82]:
df = pd.get_dummies(
    df,
    columns=cat_cols,

    dtype=int
)

In [83]:
df.head()

,Vehicle_Age,Engine_CC,Horsepower,Vehicle_Weight,Ethanol_Blend,Fuel_Price,Trip_Distance_km,Average_Speed,Engine_RPM,Tire_Pressure_PSI,...,Traffic_Level_Low,Traffic_Level_Medium,Weather_Clear,Weather_Fog,Weather_Rain,AC_Usage_No,AC_Usage_Yes,Driving_Style_Aggressive,Driving_Style_Normal,Driving_Style_Smooth
0,13.0,1000.0,82.0,1307.0,20.0,110.94,471.8,41.0,3668.0,28.5,...,0,0,0,1,0,1,0,0,1,0
1,8.0,1200.0,98.0,1493.0,20.0,98.96,494.3,54.0,1284.0,35.5,...,0,0,0,1,0,0,1,0,0,1
2,9.0,1200.0,103.0,1262.0,20.0,99.59,389.2,67.0,2469.0,33.7,...,0,1,0,1,0,0,1,1,0,0
3,14.0,1200.0,95.0,1001.0,10.0,109.11,563.2,65.0,3499.0,33.0,...,0,0,0,0,1,0,1,0,1,0
4,15.0,1800.0,148.0,1604.0,10.0,111.82,417.0,73.0,1755.0,29.0,...,0,1,0,1,0,0,1,0,0,1

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64303 entries, 0 to 64848
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Vehicle_Age                 64303 non-null  float64
 1   Engine_CC                   64303 non-null  float64
 2   Horsepower                  64303 non-null  float64
 3   Vehicle_Weight              64303 non-null  float64
 4   Ethanol_Blend               64303 non-null  float64
 5   Fuel_Price                  64303 non-null  float64
 6   Trip_Distance_km            64303 non-null  float64
 7   Average_Speed               64303 non-null  float64
 8   Engine_RPM                  64303 non-null  float64
 9   Tire_Pressure_PSI           64303 non-null  float64
 10  Temperature                 64303 non-null  float64
 11  Humidity                    64303 non-null  float64
 12  Passengers                  64303 non-null  float64
 13  Mileage_km_per_L            64303 non-null  float64
 14  Transmission_Automatic      64303 non-null  int64
 15  Transmission_Manual         64303 non-null  int64
 16  Fuel_Type_Petrol            64303 non-null  int64
 17  Maintenance_Status_Average  64303 non-null  int64
 18  Maintenance_Status_Good     64303 non-null  int64
 19  Maintenance_Status_Poor     64303 non-null  int64
 20  Road_Type_City              64303 non-null  int64
 21  Road_Type_Highway           64303 non-null  int64
 22  Road_Type_Mixed             64303 non-null  int64
 23  Road_Type_Rural             64303 non-null  int64
 24  Traffic_Level_High          64303 non-null  int64
 25  Traffic_Level_Low           64303 non-null  int64
 26  Traffic_Level_Medium        64303 non-null  int64
 27  Weather_Clear               64303 non-null  int64
 28  Weather_Fog                 64303 non-null  int64
 29  Weather_Rain                64303 non-null  int64
 30  AC_Usage_No                 64303 non-null  int64
 31  AC_Usage_Yes                64303 non-null  int64
 32  Driving_Style_Aggressive    64303 non-null  int64
 33  Driving_Style_Normal        64303 non-null  int64
 34  Driving_Style_Smooth        64303 non-null  int64
dtypes: float64(14), int64(21)
memory usage: 17.7 MB

#Feature and Target

In [85]:
X = df.drop("Mileage_km_per_L", axis=1)

y = df["Mileage_km_per_L"]

In [86]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

#Linear Regression

In [87]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# -------------------------
# Define Features and Target
# -------------------------
X = df.drop("Mileage_km_per_L", axis=1)   # Replace with your target column
y = df["Mileage_km_per_L"]

# -------------------------
# Train-Test Split
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# -------------------------
# Create Linear Regression Model
# -------------------------
lr = LinearRegression(
    fit_intercept=True,
    copy_X=True,
    n_jobs=None,
    positive=False
)
# Train Model

lr.fit(X_train, y_train)


# Prediction
y_pred = lr.predict(X_test)


# Evaluation

print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score :", r2_score(y_test, y_pred))

print("\nTraining R2 Score :", lr.score(X_train, y_train))
print("Testing R2 Score  :", lr.score(X_test, y_test))


# Model Parameters

print("\nIntercept:")
print(lr.intercept_)

print("\nCoefficients:")
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": lr.coef_
})

print(coef_df)

print("\nNumber of Features:", lr.n_features_in_)
print("Feature Names:", lr.feature_names_in_)

MAE : 0.5160658785186958
MSE : 0.38074892304591135
RMSE: 0.6170485580940218
R2 Score : 0.9690626369754447

Training R2 Score : 0.967057614121158
Testing R2 Score  : 0.9690626369754447

Intercept:
34.084251228516464

Coefficients:
                       Feature   Coefficient
0                  Vehicle_Age -1.983544e-01
1                    Engine_CC -3.954561e-03
2                   Horsepower -1.681465e-04
3               Vehicle_Weight -5.517042e-03
4                Ethanol_Blend -5.466447e-02
5                   Fuel_Price -3.807929e-04
6             Trip_Distance_km  2.874722e-05
7                Average_Speed  1.907734e-05
8                   Engine_RPM -4.312951e-08
9            Tire_Pressure_PSI -7.770268e-04
10                 Temperature -1.278158e-04
11                    Humidity -1.012163e-04
12                  Passengers -2.551520e-03
13      Transmission_Automatic -1.666381e-03
14         Transmission_Manual  1.666381e-03
15            Fuel_Type_Petrol  0.000000e+00
16  Maintenance_Status_Average  6.604399e-02
17     Maintenance_Status_Good  8.637591e-01
18     Maintenance_Status_Poor -9.298031e-01
19              Road_Type_City -2.231133e+00
20           Road_Type_Highway  1.738293e+00
21             Road_Type_Mixed  2.417289e-01
22             Road_Type_Rural  2.511106e-01
23          Traffic_Level_High -1.061019e+00
24           Traffic_Level_Low  9.342189e-01
25        Traffic_Level_Medium  1.268002e-01
26               Weather_Clear  3.413950e-03
27                 Weather_Fog -4.931410e-03
28                Weather_Rain  1.517460e-03
29                 AC_Usage_No  4.937474e-01
30                AC_Usage_Yes -4.937474e-01
31    Driving_Style_Aggressive -1.663356e+00
32        Driving_Style_Normal  3.397236e-01
33        Driving_Style_Smooth  1.323632e+00

Number of Features: 34
Feature Names: ['Vehicle_Age' 'Engine_CC' 'Horsepower' 'Vehicle_Weight' 'Ethanol_Blend'
 'Fuel_Price' 'Trip_Distance_km' 'Average_Speed' 'Engine_RPM'
 'Tire_Pressure_PSI' 'Temperature' 'Humidity' 'Passengers'
 'Transmission_Automatic' 'Transmission_Manual' 'Fuel_Type_Petrol'
 'Maintenance_Status_Average' 'Maintenance_Status_Good'
 'Maintenance_Status_Poor' 'Road_Type_City' 'Road_Type_Highway'
 'Road_Type_Mixed' 'Road_Type_Rural' 'Traffic_Level_High'
 'Traffic_Level_Low' 'Traffic_Level_Medium' 'Weather_Clear' 'Weather_Fog'
 'Weather_Rain' 'AC_Usage_No' 'AC_Usage_Yes' 'Driving_Style_Aggressive'
 'Driving_Style_Normal' 'Driving_Style_Smooth']

#Random Forest

In [88]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# -----------------------------
# Define Features and Target
# -----------------------------
X = df.drop("Mileage_km_per_L", axis=1)      # Replace with your target column
y = df["Mileage_km_per_L"]

# -----------------------------
# Split the Dataset
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# -----------------------------
# Create Random Forest Model
# -----------------------------
rf = RandomForestRegressor(
    n_estimators=200,
    criterion='squared_error',
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    bootstrap=True,
    random_state=42,

)

# -----------------------------
# Train the Model
# -----------------------------
rf.fit(X_train, y_train)

# -----------------------------
# Prediction
# -----------------------------
y_pred = rf.predict(X_test)

# -----------------------------
# Model Evaluation
# -----------------------------
print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score :", r2_score(y_test, y_pred))

print("\nTraining R2 Score :", rf.score(X_train, y_train))
print("Testing R2 Score :", rf.score(X_test, y_test))

# -----------------------------
# Feature Importance
# -----------------------------
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

print("\nFeature Importance")
print(importance)

# -----------------------------
# Model Parameters
# -----------------------------
print("\nModel Parameters")
print(rf.get_params())

MAE : 1.0874002107210312
MSE : 1.8467448154807151
RMSE: 1.358949894396668
R2 Score : 0.8499446451136697

Training R2 Score : 0.8677630105087895
Testing R2 Score : 0.8499446451136697

Feature Importance
                       Feature  Importance
4                Ethanol_Blend    0.150655
19              Road_Type_City    0.131558
3               Vehicle_Weight    0.128443
2                   Horsepower    0.110298
1                    Engine_CC    0.104217
31    Driving_Style_Aggressive    0.084945
0                  Vehicle_Age    0.049087
20           Road_Type_Highway    0.048541
33        Driving_Style_Smooth    0.042177
23          Traffic_Level_High    0.030766
24           Traffic_Level_Low    0.019238
18     Maintenance_Status_Poor    0.019137
17     Maintenance_Status_Good    0.014547
32        Driving_Style_Normal    0.013463
29                 AC_Usage_No    0.008334
30                AC_Usage_Yes    0.008307
21             Road_Type_Mixed    0.004941
22             Road_Type_Rural    0.004321
25        Traffic_Level_Medium    0.003144
8                   Engine_RPM    0.003111
6             Trip_Distance_km    0.002993
5                   Fuel_Price    0.002983
9            Tire_Pressure_PSI    0.002703
7                Average_Speed    0.002620
11                    Humidity    0.002484
10                 Temperature    0.002190
16  Maintenance_Status_Average    0.001973
12                  Passengers    0.001090
26               Weather_Clear    0.000362
27                 Weather_Fog    0.000351
13      Transmission_Automatic    0.000350
28                Weather_Rain    0.000341
14         Transmission_Manual    0.000330
15            Fuel_Type_Petrol    0.000000

Model Parameters
{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': 10, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 2, 'min_samples_split': 5, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 200, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

#Decision Tree

In [89]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# -----------------------------
# Define Features and Target
# -----------------------------
X = df.drop("Mileage_km_per_L", axis=1)   # Replace with your target column
y = df["Mileage_km_per_L"]

# -----------------------------
# Split the Dataset
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# -----------------------------
# Create Decision Tree Model
# -----------------------------
dt = DecisionTreeRegressor(
    criterion='squared_error',
    splitter='best',
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    max_features='sqrt',
    random_state=42
)

# -----------------------------
# Train the Model
# -----------------------------
dt.fit(X_train, y_train)

# -----------------------------
# Prediction
# -----------------------------
y_pred = dt.predict(X_test)

# -----------------------------
# Evaluation
# -----------------------------
print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score :", r2_score(y_test, y_pred))

print("\nTraining R2 Score :", dt.score(X_train, y_train))
print("Testing R2 Score :", dt.score(X_test, y_test))

# -----------------------------
# Feature Importance
# -----------------------------
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": dt.feature_importances_
}).sort_values(by="Importance", ascending=False)

print("\nFeature Importance")
print(importance)

# -----------------------------
# Model Parameters
# -----------------------------
print("\nModel Parameters")
print(dt.get_params())

MAE : 2.2285307074840466
MSE : 7.686181758146575
RMSE: 2.77239639268027
R2 Score : 0.3754671886601182

Training R2 Score : 0.3917657897250738
Testing R2 Score : 0.3754671886601182

Feature Importance
                       Feature    Importance
4                Ethanol_Blend  2.372528e-01
20           Road_Type_Highway  2.063939e-01
19              Road_Type_City  1.457214e-01
1                    Engine_CC  7.737395e-02
2                   Horsepower  6.544596e-02
31    Driving_Style_Aggressive  6.316067e-02
18     Maintenance_Status_Poor  6.309537e-02
24           Traffic_Level_Low  3.168648e-02
33        Driving_Style_Smooth  3.161158e-02
3               Vehicle_Weight  3.130870e-02
30                AC_Usage_Yes  1.398851e-02
23          Traffic_Level_High  1.389452e-02
22             Road_Type_Rural  1.051023e-02
0                  Vehicle_Age  5.554114e-03
16  Maintenance_Status_Average  2.343619e-03
32        Driving_Style_Normal  3.807883e-04
5                   Fuel_Price  2.771624e-04
14         Transmission_Manual  2.044253e-07
17     Maintenance_Status_Good  0.000000e+00
15            Fuel_Type_Petrol  0.000000e+00
12                  Passengers  0.000000e+00
13      Transmission_Automatic  0.000000e+00
11                    Humidity  0.000000e+00
10                 Temperature  0.000000e+00
8                   Engine_RPM  0.000000e+00
9            Tire_Pressure_PSI  0.000000e+00
7                Average_Speed  0.000000e+00
6             Trip_Distance_km  0.000000e+00
25        Traffic_Level_Medium  0.000000e+00
21             Road_Type_Mixed  0.000000e+00
29                 AC_Usage_No  0.000000e+00
28                Weather_Rain  0.000000e+00
27                 Weather_Fog  0.000000e+00
26               Weather_Clear  0.000000e+00

Model Parameters
{'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': 5, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 5, 'min_samples_split': 10, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'random_state': 42, 'splitter': 'best'}

#I compared three regression models: Decision Tree, Random Forest, and Linear Regression using MAE, MSE, RMSE, and R² score. Linear Regression achieved the best performance with a testing R² score of 96.41%, along with the lowest MAE (0.5165), MSE (0.4159), and RMSE (0.6449). The training R² (96.59%) and testing R² (96.41%) were almost identical, indicating excellent generalization without overfitting. Random Forest performed reasonably well with a testing R² of 84.96%, while the Decision Tree underfitted the data with a testing R² of 37.30%. Therefore, Linear Regression was selected as the final model because it provided the highest prediction accuracy and the best balance between training and testing performance.

#Save the Best Model

In [90]:
import joblib

joblib.dump(LinearRegression, "best_mileage_model.pkl")

print("Model Saved Successfully")

Model Saved Successfully

In [91]:
import os

print(os.getcwd())

/content