In [6]:
import pandas as pd
import numpy as np

path = r"D:\Vehicle_Mileage_Project\data\raw\ML Dataset.xlsx"

df = pd.read_excel(path)

df.head()

,Vehicle_ID,Manufacturer,Model,Vehicle_Age,Engine_CC,Horsepower,Vehicle_Weight,Transmission,Fuel_Type,Ethanol_Blend,...,Traffic_Level,Temperature,Humidity,Weather,AC_Usage,Driving_Style,Passengers,CO2_Emission_g_km,Fuel_Consumption_L_100km,Mileage_km_per_L
0,V014767,Tata,Nexon,13.0,1000.0,82.0,1307.0,Automatic,Petrol,20.0,...,High,27.0,61.0,Fog,No,Normal,1.0,192.1,5.00,20.02
1,V020736,Toyota,Glanza,8.0,1200.0,98.0,1493.0,Automatic,Petrol,20.0,...,High,30.0,48.0,Fog,Yes,Smooth,3.0,189.2,5.12,19.52
2,V041583,Maruti,Baleno,9.0,1200.0,103.0,1262.0,Automatic,Petrol,20.0,...,Medium,34.0,44.0,Fog,Yes,Aggressive,1.0,197.3,5.55,18.01
3,V042258,Honda,City,14.0,1200.0,95.0,1001.0,Manual,Petrol,10.0,...,High,15.0,53.0,Rain,Yes,Normal,1.0,185.8,5.23,19.12
4,V029600,Tata,Altroz,15.0,1800.0,148.0,1604.0,Manual,Petrol,10.0,...,Medium,24.0,65.0,Fog,Yes,Smooth,1.0,197.7,5.90,16.96

In [7]:
df.head

<bound method NDFrame.head of       Vehicle_ID Manufacturer   Model  Vehicle_Age  Engine_CC  Horsepower  \
0        V014767         Tata   Nexon         13.0     1000.0        82.0
1        V020736       Toyota  Glanza          8.0     1200.0        98.0
2        V041583       Maruti  Baleno          9.0     1200.0       103.0
3        V042258        Honda    City         14.0     1200.0        95.0
4        V029600         Tata  Altroz         15.0     1800.0       148.0
...          ...          ...     ...          ...        ...         ...
64844    V062571       Toyota  Glanza          0.0     1200.0        98.0
64845    V038159        Honda    City         14.0     2000.0       161.0
64846    V000861        Honda    City          7.0     1800.0       153.0
64847    V015796         Tata  Altroz          9.0     2000.0       168.0
64848    V056423       Maruti  Baleno          7.0     1500.0       122.0

       Vehicle_Weight Transmission Fuel_Type  Ethanol_Blend  ...  \
0              1307.0    Automatic    Petrol           20.0  ...
1              1493.0    Automatic    Petrol           20.0  ...
2              1262.0    Automatic    Petrol           20.0  ...
3              1001.0       Manual    Petrol           10.0  ...
4              1604.0       Manual    Petrol           10.0  ...
...               ...          ...       ...            ...  ...
64844          1683.0    Automatic    Petrol           30.0  ...
64845          1321.0    Automatic    Petrol           50.0  ...
64846          1114.0       Manual    Petrol           85.0  ...
64847          1224.0    Automatic    Petrol           30.0  ...
64848          1198.0       Manual    Petrol           10.0  ...

       Traffic_Level  Temperature  Humidity  Weather  AC_Usage Driving_Style  \
0               High         27.0      61.0      Fog        No        Normal
1               High         30.0      48.0      Fog       Yes        Smooth
2             Medium         34.0      44.0      Fog       Yes    Aggressive
3               High         15.0      53.0     Rain       Yes        Normal
4             Medium         24.0      65.0      Fog       Yes        Smooth
...              ...          ...       ...      ...       ...           ...
64844         Medium         30.0      38.0    Clear        No        Smooth
64845         Medium         40.0      63.0      Fog        No    Aggressive
64846           High         20.0      75.0    Clear        No        Normal
64847         Medium         27.0      39.0      Fog        No        Smooth
64848            Low         21.0      32.0      Fog        No        Normal

      Passengers CO2_Emission_g_km  Fuel_Consumption_L_100km  Mileage_km_per_L
0            1.0             192.1                      5.00             20.02
1            3.0             189.2                      5.12             19.52
2            1.0             197.3                      5.55             18.01
3            1.0             185.8                      5.23             19.12
4            1.0             197.7                      5.90             16.96
...          ...               ...                       ...               ...
64844        3.0             183.9                      4.48             22.33
64845        4.0             278.9                      9.43             10.60
64846        5.0             250.5                      6.78             14.74
64847        4.0             196.6                      5.31             18.84
64848        4.0             180.9                      4.89             20.45

[64849 rows x 27 columns]>

In [8]:
df.tail

<bound method NDFrame.tail of       Vehicle_ID Manufacturer   Model  Vehicle_Age  Engine_CC  Horsepower  \
0        V014767         Tata   Nexon         13.0     1000.0        82.0
1        V020736       Toyota  Glanza          8.0     1200.0        98.0
2        V041583       Maruti  Baleno          9.0     1200.0       103.0
3        V042258        Honda    City         14.0     1200.0        95.0
4        V029600         Tata  Altroz         15.0     1800.0       148.0
...          ...          ...     ...          ...        ...         ...
64844    V062571       Toyota  Glanza          0.0     1200.0        98.0
64845    V038159        Honda    City         14.0     2000.0       161.0
64846    V000861        Honda    City          7.0     1800.0       153.0
64847    V015796         Tata  Altroz          9.0     2000.0       168.0
64848    V056423       Maruti  Baleno          7.0     1500.0       122.0

       Vehicle_Weight Transmission Fuel_Type  Ethanol_Blend  ...  \
0              1307.0    Automatic    Petrol           20.0  ...
1              1493.0    Automatic    Petrol           20.0  ...
2              1262.0    Automatic    Petrol           20.0  ...
3              1001.0       Manual    Petrol           10.0  ...
4              1604.0       Manual    Petrol           10.0  ...
...               ...          ...       ...            ...  ...
64844          1683.0    Automatic    Petrol           30.0  ...
64845          1321.0    Automatic    Petrol           50.0  ...
64846          1114.0       Manual    Petrol           85.0  ...
64847          1224.0    Automatic    Petrol           30.0  ...
64848          1198.0       Manual    Petrol           10.0  ...

       Traffic_Level  Temperature  Humidity  Weather  AC_Usage Driving_Style  \
0               High         27.0      61.0      Fog        No        Normal
1               High         30.0      48.0      Fog       Yes        Smooth
2             Medium         34.0      44.0      Fog       Yes    Aggressive
3               High         15.0      53.0     Rain       Yes        Normal
4             Medium         24.0      65.0      Fog       Yes        Smooth
...              ...          ...       ...      ...       ...           ...
64844         Medium         30.0      38.0    Clear        No        Smooth
64845         Medium         40.0      63.0      Fog        No    Aggressive
64846           High         20.0      75.0    Clear        No        Normal
64847         Medium         27.0      39.0      Fog        No        Smooth
64848            Low         21.0      32.0      Fog        No        Normal

      Passengers CO2_Emission_g_km  Fuel_Consumption_L_100km  Mileage_km_per_L
0            1.0             192.1                      5.00             20.02
1            3.0             189.2                      5.12             19.52
2            1.0             197.3                      5.55             18.01
3            1.0             185.8                      5.23             19.12
4            1.0             197.7                      5.90             16.96
...          ...               ...                       ...               ...
64844        3.0             183.9                      4.48             22.33
64845        4.0             278.9                      9.43             10.60
64846        5.0             250.5                      6.78             14.74
64847        4.0             196.6                      5.31             18.84
64848        4.0             180.9                      4.89             20.45

[64849 rows x 27 columns]>

In [9]:
df.describe()

,Vehicle_Age,Engine_CC,Horsepower,Vehicle_Weight,Ethanol_Blend,Fuel_Price,Trip_Distance_km,Average_Speed,Engine_RPM,Tire_Pressure_PSI,Temperature,Humidity,Passengers,CO2_Emission_g_km,Fuel_Consumption_L_100km,Mileage_km_per_L
count,64554.000000,64848.000000,64845.000000,64847.000000,64848.000000,64848.000000,64846.000000,64846.000000,64844.000000,64847.000000,64847.000000,64846.000000,64845.000000,64848.000000,64848.000000,64515.000000
mean,7.485315,1503.878300,125.114427,1274.431107,38.918779,102.495828,302.720027,64.890695,2495.715810,31.996951,28.567937,60.050489,2.997348,213.981236,6.022604,17.392228
std,4.621749,368.608256,30.801036,245.866585,26.522092,7.193345,171.994817,26.258180,752.938352,2.323987,8.065794,17.606741,1.417620,31.651761,1.427117,3.506301
min,0.000000,1000.000000,78.000000,850.000000,10.000000,90.000000,5.000000,20.000000,1200.000000,28.000000,15.000000,30.000000,1.000000,152.600000,3.400000,7.000000
25%,3.000000,1200.000000,97.000000,1061.000000,20.000000,96.270000,153.300000,42.000000,1841.000000,30.000000,22.000000,45.000000,2.000000,191.200000,5.040000,15.020000
50%,7.000000,1500.000000,125.000000,1274.000000,30.000000,102.480000,302.600000,65.000000,2500.000000,32.000000,29.000000,60.000000,3.000000,207.800000,5.730000,17.450000
75%,12.000000,1800.000000,153.000000,1488.000000,50.000000,108.720000,451.600000,88.000000,3147.000000,34.000000,36.000000,75.000000,4.000000,230.000000,6.660000,19.830000
max,15.000000,2000.000000,171.000000,1700.000000,85.000000,115.000000,600.000000,110.000000,3800.000000,36.000000,42.000000,90.000000,5.000000,385.900000,14.290000,29.390000

In [10]:
df.shape

(64849, 27)

In [11]:
df.columns

Index(['Vehicle_ID', 'Manufacturer', 'Model', 'Vehicle_Age', 'Engine_CC',
       'Horsepower', 'Vehicle_Weight', 'Transmission', 'Fuel_Type',
       'Ethanol_Blend', 'Fuel_Price', 'Trip_Distance_km', 'Average_Speed',
       'Engine_RPM', 'Tire_Pressure_PSI', 'Maintenance_Status', 'Road_Type',
       'Traffic_Level', 'Temperature', 'Humidity', 'Weather', 'AC_Usage',
       'Driving_Style', 'Passengers', 'CO2_Emission_g_km',
       'Fuel_Consumption_L_100km', 'Mileage_km_per_L'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64849 entries, 0 to 64848
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Vehicle_ID                64848 non-null  str
 1   Manufacturer              64847 non-null  str
 2   Model                     64848 non-null  str
 3   Vehicle_Age               64554 non-null  float64
 4   Engine_CC                 64848 non-null  float64
 5   Horsepower                64845 non-null  float64
 6   Vehicle_Weight            64847 non-null  float64
 7   Transmission              64846 non-null  str
 8   Fuel_Type                 64848 non-null  str
 9   Ethanol_Blend             64848 non-null  float64
 10  Fuel_Price                64848 non-null  float64
 11  Trip_Distance_km          64846 non-null  float64
 12  Average_Speed             64846 non-null  float64
 13  Engine_RPM                64844 non-null  float64
 14  Tire_Pressure_PSI         64847 non-null  float64
 15  Maintenance_Status        64847 non-null  str
 16  Road_Type                 64847 non-null  str
 17  Traffic_Level             64849 non-null  str
 18  Temperature               64847 non-null  float64
 19  Humidity                  64846 non-null  float64
 20  Weather                   64845 non-null  str
 21  AC_Usage                  64848 non-null  str
 22  Driving_Style             64848 non-null  str
 23  Passengers                64845 non-null  float64
 24  CO2_Emission_g_km         64848 non-null  float64
 25  Fuel_Consumption_L_100km  64848 non-null  float64
 26  Mileage_km_per_L          64515 non-null  float64
dtypes: float64(16), str(11)
memory usage: 17.1 MB

In [13]:
df.describe()

,Vehicle_Age,Engine_CC,Horsepower,Vehicle_Weight,Ethanol_Blend,Fuel_Price,Trip_Distance_km,Average_Speed,Engine_RPM,Tire_Pressure_PSI,Temperature,Humidity,Passengers,CO2_Emission_g_km,Fuel_Consumption_L_100km,Mileage_km_per_L
count,64554.000000,64848.000000,64845.000000,64847.000000,64848.000000,64848.000000,64846.000000,64846.000000,64844.000000,64847.000000,64847.000000,64846.000000,64845.000000,64848.000000,64848.000000,64515.000000
mean,7.485315,1503.878300,125.114427,1274.431107,38.918779,102.495828,302.720027,64.890695,2495.715810,31.996951,28.567937,60.050489,2.997348,213.981236,6.022604,17.392228
std,4.621749,368.608256,30.801036,245.866585,26.522092,7.193345,171.994817,26.258180,752.938352,2.323987,8.065794,17.606741,1.417620,31.651761,1.427117,3.506301
min,0.000000,1000.000000,78.000000,850.000000,10.000000,90.000000,5.000000,20.000000,1200.000000,28.000000,15.000000,30.000000,1.000000,152.600000,3.400000,7.000000
25%,3.000000,1200.000000,97.000000,1061.000000,20.000000,96.270000,153.300000,42.000000,1841.000000,30.000000,22.000000,45.000000,2.000000,191.200000,5.040000,15.020000
50%,7.000000,1500.000000,125.000000,1274.000000,30.000000,102.480000,302.600000,65.000000,2500.000000,32.000000,29.000000,60.000000,3.000000,207.800000,5.730000,17.450000
75%,12.000000,1800.000000,153.000000,1488.000000,50.000000,108.720000,451.600000,88.000000,3147.000000,34.000000,36.000000,75.000000,4.000000,230.000000,6.660000,19.830000
max,15.000000,2000.000000,171.000000,1700.000000,85.000000,115.000000,600.000000,110.000000,3800.000000,36.000000,42.000000,90.000000,5.000000,385.900000,14.290000,29.390000

In [14]:
df.describe(include="object")

C:\Users\sujee\AppData\Local\Temp\ipykernel_7328\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Vehicle_ID,Manufacturer,Model,Transmission,Fuel_Type,Maintenance_Status,Road_Type,Traffic_Level,Weather,AC_Usage,Driving_Style
count,64848,64847,64848,64846,64848,64847,64847,64849,64845,64848,64848
unique,64302,5,8,2,1,3,4,3,3,2,3
top,V059128,Tata,Glanza,Automatic,Petrol,Good,City,Low,Clear,Yes,Aggressive
freq,2,13080,13028,32512,64848,21801,16348,21649,21623,32503,21802

In [15]:
df.dtypes

Vehicle_ID                      str
Manufacturer                    str
Model                           str
Vehicle_Age                 float64
Engine_CC                   float64
Horsepower                  float64
Vehicle_Weight              float64
Transmission                    str
Fuel_Type                       str
Ethanol_Blend               float64
Fuel_Price                  float64
Trip_Distance_km            float64
Average_Speed               float64
Engine_RPM                  float64
Tire_Pressure_PSI           float64
Maintenance_Status              str
Road_Type                       str
Traffic_Level                   str
Temperature                 float64
Humidity                    float64
Weather                         str
AC_Usage                        str
Driving_Style                   str
Passengers                  float64
CO2_Emission_g_km           float64
Fuel_Consumption_L_100km    float64
Mileage_km_per_L            float64
dtype: object

In [16]:
df.isnull().sum()

Vehicle_ID                    1
Manufacturer                  2
Model                         1
Vehicle_Age                 295
Engine_CC                     1
Horsepower                    4
Vehicle_Weight                2
Transmission                  3
Fuel_Type                     1
Ethanol_Blend                 1
Fuel_Price                    1
Trip_Distance_km              3
Average_Speed                 3
Engine_RPM                    5
Tire_Pressure_PSI             2
Maintenance_Status            2
Road_Type                     2
Traffic_Level                 0
Temperature                   2
Humidity                      3
Weather                       4
AC_Usage                      1
Driving_Style                 1
Passengers                    4
CO2_Emission_g_km             1
Fuel_Consumption_L_100km      1
Mileage_km_per_L            334
dtype: int64

In [17]:
df.isnull().sum().sum()

np.int64(680)

In [18]:
# Check duplicate rows
df.duplicated().sum()

np.int64(546)

In [19]:
# Check unique values in each column
df.nunique()

Vehicle_ID                  64302
Manufacturer                    5
Model                           8
Vehicle_Age                    16
Engine_CC                       5
Horsepower                     55
Vehicle_Weight                851
Transmission                    2
Fuel_Type                       1
Ethanol_Blend                   5
Fuel_Price                   2501
Trip_Distance_km             5951
Average_Speed                  91
Engine_RPM                   2601
Tire_Pressure_PSI              81
Maintenance_Status              3
Road_Type                       4
Traffic_Level                   3
Temperature                    28
Humidity                       61
Weather                         3
AC_Usage                        2
Driving_Style                   3
Passengers                      5
CO2_Emission_g_km            2002
Fuel_Consumption_L_100km      926
Mileage_km_per_L             2009
dtype: int64